from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from utils.enums import RiskLevel, Recommendation


@dataclass(kw_only=True)
class RiskAssessment:
    """
    Final output generated by the Risk Agent.

    This model contains both the structured rule-based assessment
    and the AI-generated explanation presented to officers.
    """

    # -----------------------------
    # Core Assessment
    # -----------------------------
    risk_level: RiskLevel

    risk_score: float

    confidence_score: float

    recommendation: Recommendation

    reasons: list[str]

    generated_at: datetime = field(default_factory=datetime.now)

    # -----------------------------
    # Explainability
    # -----------------------------
    llm_explanation: Optional[str] = None

    supporting_policy: list[str] = field(default_factory=list)

    triggered_rules: list[str] = field(default_factory=list)

    evidence: list[str] = field(default_factory=list)

    # -----------------------------
    # Human Review
    # -----------------------------
    requires_manual_review: bool = False

    manual_review_reason: Optional[str] = None

    # -----------------------------
    # Metadata
    # -----------------------------
    model_version: Optional[str] = None

    inference_time_ms: Optional[float] = None

    metadata: dict = field(default_factory=dict)